import './globals.css';

import { Inter } from 'next/font/google';
import { Source_Code_Pro } from 'next/font/google';

const inter = Inter({subsets: ['latin'], variable: '--font-inter'})
const source_code_pro = Source_Code_Pro({ subsets: ['latin'], variable: '--font-source-code-pro' });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${inter.variable} ${source_code_pro.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
